#Feature: Login Functionality for OpenCart E-commerce Website
#
#  As a user of the OpenCart website
#  I want to be able to log in with my account
#  So that I can access my account-related features and manage my orders
#
#  Background:
#    Given I am on the login page
#
#  @wip
#  Scenario: Successful login with valid credentials
#    Given User have entered a valid username and password
#      | abhisek | test@123 |
#    When User click on the login button
#    Then User should be logged in successfully